### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ystraore**
Hi Bro,
Please have a look on my code. I am also done with it.

Thanks!

### CODE REVIEW

**Comment by Ces-Borrego** [comment]
The code looks good, there is a comment you left in regards to an unfinished method. Not sure if you just forgot, I thought I would remind you just in case. End to end test looks good.

**Comment by Ces-Borrego** [comment]
I meant to merge the pull request with a comment, I did not mean to close it. Will merge the request if you need to send it again.

**Comment by ystraore** [comment]
Hi bro,
Thanks for letting me know  about the comment. It was an comment I left on my first commit message. Everything is fixed and good to go. I got surprised that the changes I made to my second commit did not get updated.

BTW, I reopen the pull request if you want to add any comment later on.

**Comment by Ces-Borrego** [comment]
Great, glad to hear it. Nice work.

**Pull request merged**
